### ISSUE TITLE
IDEE: Bilder in der Liste (klein) und in der Editieransicht ausgeben

### ISSUE THREAD

**Issue by olien** [KLXM/oneFileYFormCRUD#4]

**Comment by skerbis** [comment]
Für die Editieransicht braucht es ein Widget / Value das das kann. 
Die Liste könnte man evtl. so erweitern dass man ein Bildfeld angeben kann, welches am Anfang der Liste ausgegeben werden soll.

**Comment by skerbis** [comment]
Quatsch ist doch schon da ;-) 


```php
$renderer->setFormatCallback('image', function($value) {
    return '<img src="/path/' . htmlspecialchars($value) . '">';
});
```

**Comment by AWqxKAWERbXo** [comment]
yform_field bietet ein passendes Value.

**Comment by skerbis** [comment]
@olien was @alxndr-w sagt mal testen ...

**Comment by skerbis** [comment]
@alxndr-w es geht um das Frontend und Upload und Vorschau

**Comment by AWqxKAWERbXo** [comment]
Achso. Aber das ist doch kein Thema hiervon. Das muss doch wenn, dann der Wurzel gepackt und gelöst werden -> YForm

**Comment by skerbis** [comment]
Jupp

**Comment by skerbis** [comment]
Hat sich erledigt

**Comment by AWqxKAWERbXo** [comment]
Wie?

**Comment by skerbis** [comment]
Es kann nicht Teil des addons sein extra dafür values bereitzustellen die allgemein gebraucht werden. Die Liste selbst kann man über den callback beeinflussen
